apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weekly-digest-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: weekly-digest
    spec:
      containers:
      - name: weekly-digest
        image: oydeu/weekly-digest:0.3
        ports:
        - containerPort: 3000
        env:
          - name: RAILS_ENV
            value: production
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: railsapp-secrets
                key: secret-key-base
